version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: schemars
    versions:
    - 0.8.2
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: reqwest
    versions:
    - 0.10.9
    - 0.11.2
  - dependency-name: mockito
    versions:
    - 0.29.0
  - dependency-name: serde
    versions:
    - 1.0.122
    - 1.0.123
    - 1.0.124
  - dependency-name: async-trait
    versions:
    - 0.1.42
    - 0.1.47
    - 0.1.48
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: futures-util
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: url
    versions:
    - 2.2.0
    - 2.2.1
  - dependency-name: async-std
    versions:
    - 1.9.0
