stages:
  - test
  - publish
  - benchmark

include:
  - project: 'media-cloud-ai/ci/pipelines'
    file: '/rust/rust-publish-docker.yml'
  - project: 'media-cloud-ai/ci/pipelines'
    file: '/rust/rust-base.yml'

build:format:
  stage: test
  script: cargo fmt -- --check

build:coverage:
  stage: test
  script: cargo tarpaulin --avoid-cfg-tarpaulin --out Xml --all-features
  after_script:
    - apt-get install -y curl
    - bash <(curl -s https://codecov.io/bash)
  coverage: '/^\d+.\d+% coverage/'

benchmark:
  stage: benchmark
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - export VERSION=`cargo pkgid | cut -d# -f2 | cut -d':' -f2`
    - if [ "$VERSION" != "$CI_BUILD_TAG" ]; then exit -1; fi
    - docker info
    - docker-compose version
  script:
    - docker build -t transfer_worker_benches -f ./benches/Dockerfile .
    - docker-compose up -d
    - docker run --rm transfer_worker_benches
    - docker-compose down
  only:
    - tags
