variables:
  MEDIA_FEATURE_DEPENDENCIES: "clang libavutil-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libpostproc-dev libswresample-dev ffmpeg"


stages:
  - test
  - publish
  - benchmark

include:
  - project: 'media-cloud-ai/ci/pipelines'
    file: '/rust/rust-publish-docker.yml'
  - project: 'media-cloud-ai/ci/pipelines'
    file: '/rust/rust-base.yml'

build:test:
  stage: test
  script: cargo test && cd rs_transfer && cargo test

build:format:
  stage: test
  script: cargo fmt -- --check && cd rs_transfer && cargo fmt -- --check

build:clippy:
  stage: test
  before_script:
    - apt-get update -q && apt-get install ${MEDIA_FEATURE_DEPENDENCIES} -y
  script: cargo clippy --all-targets --all-features -- -D warnings

build:coverage:
  stage: test
  before_script:
    - apt-get update -q && apt-get install ${MEDIA_FEATURE_DEPENDENCIES} -y
  script: cargo tarpaulin --avoid-cfg-tarpaulin --out Xml --all-features && cd rs_transfer && cargo tarpaulin --avoid-cfg-tarpaulin --out Xml --all-features
  after_script:
    - apt-get install -y curl
    - bash <(curl -s https://codecov.io/bash)
  coverage: '/^\d+.\d+% coverage/'

benchmark:
  stage: benchmark
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose version
  script:
    - docker build -t transfer_worker_benches -f ./benches/Dockerfile .
    - docker-compose up -d
    - docker run --rm transfer_worker_benches
    - docker-compose down
  only:
    - tags
