[package]
name = "transfer_worker"
version = "0.4.1"
authors = [
  "Valentin Noel <valentin.noel@media-io.com>",
  "Marc-Antoine Arnaud <maarnaud@media-io.com>",
]
edition = "2018"

[lib]
crate-type = ["lib"]

[[bin]]
name = "transfer_worker"
path = "src/bin/main.rs"

[dependencies]
async-std = { version = "1.5.0", features = ["unstable"]}
async-trait = "0.1.31"
bytes = "0.5.4"
ftp = { version = "3.0.1", features = ["secure"], path = "rust-ftp" }
futures = "0.3"
futures-util = "0.3"
mcai_worker_sdk = "0.11.10"
reqwest = "0.10"
rusoto_core = "0.45"
rusoto_credential = "0.45"
rusoto_s3 = "0.46"
schemars = "0.8.0"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
ssh-transfer = "0.1.1"
threadpool = "1.8"
tokio = "0.2"
tokio-io = "0.1"
url = "2.1.1"

[dev-dependencies]
mockito = "0.27"
rusoto_mock = "0.45"
criterion = "0.3"

[build-dependencies]
built = "0.4"

[[bench]]
name = "transfer_worker_benchmark"
harness = false
