[package]
name = "rs_transfer_worker"
version = "0.0.1"
authors = [
    "Valentin Noel <valentin.noel@media-io.com>",
    "Marc-Antoine Arnaud <maarnaud@media-io.com>",
    "Thibaud Le Graverend <thibaud.legraverend@media-io.com>",
]
edition = "2018"

[workspace]
members = [
    "rs_transfer",
]

[dependencies]
async-std = { version = "1.5.0", features = ["unstable"]}
criterion = "0.3.5"
rs_transfer = { version = "0.4.2", path = "rs_transfer" }
mcai_worker_sdk = "1.1.1"
schemars = "0.8.0"
serde = { version = "^1.0", features = ["derive"] }
tokio = "1.7"
tokio-io = "0.1"

[build-dependencies]
built = "0.4"


[[bench]]
name = "transfer_worker_benchmark"
harness = false
