[package]
name = "transfer_worker"

version = "0.2.0"
authors = [
  "Valentin Noel <valentin.noel@media-io.com>",
  "Marc-Antoine Arnaud <maarnaud@media-io.com>",
]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = ["unstable"]}
async-trait = "0.1.31"
bytes = "0.5.4"
ftp = { version = "3.0.1", features = ["secure"], path = "rust-ftp" }
futures = "0.3"
futures-util = "0.3"
mcai_worker_sdk = "0.10.4"
reqwest = "0.10"
rusoto_core = "0.42"
rusoto_credential = "0.42"
rusoto_s3 = "0.42"
threadpool = "1.8"
tokio = "0.2"
tokio-io = "0.1"
url = "2.1.1"

[dev-dependencies]
mockito = "0.25"
rusoto_mock = "0.43"

[build-dependencies]
built = "0.4"
