version: '3'
services:
  ftp_vsftpd:
    image: delfer/alpine-ftp-server
    container_name: ftp_vsftpd
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - "USERS=ftp_user|ftp_password|/data"
    volumes:
      - ./ftp/:/data
    restart: always

  http_nginx:
    image: nginx
    container_name: http_nginx
    ports:
      - "8080:80"
    volumes:
      - ./http/:/usr/share/nginx/html
    restart: always

  s3_minio:
    image: minio/minio
    container_name: s3_minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      - "MINIO_ACCESS_KEY=S3_SERVER_ACCESS_KEY"
      - "MINIO_SECRET_KEY=S3_SERVER_SECRET_KEY"
    command: server /data
